#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Prozess.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.loadramanbtn = QtWidgets.QPushButton(self.centralwidget)
        self.loadramanbtn.setGeometry(QtCore.QRect(30, 40, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.loadramanbtn.setFont(font)
        self.loadramanbtn.setObjectName("loadramanbtn")
        self.loadbrechbtn = QtWidgets.QPushButton(self.centralwidget)
        self.loadbrechbtn.setGeometry(QtCore.QRect(630, 40, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.loadbrechbtn.setFont(font)
        self.loadbrechbtn.setObjectName("loadbrechbtn")
        self.auswertungbtn = QtWidgets.QPushButton(self.centralwidget)
        self.auswertungbtn.setGeometry(QtCore.QRect(30, 220, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.auswertungbtn.setFont(font)
        self.auswertungbtn.setObjectName("auswertungbtn")
        self.detailbtn = QtWidgets.QPushButton(self.centralwidget)
        self.detailbtn.setGeometry(QtCore.QRect(30, 320, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.detailbtn.setFont(font)
        self.detailbtn.setObjectName("detailbtn")
        self.datenfusionbtn = QtWidgets.QPushButton(self.centralwidget)
        self.datenfusionbtn.setGeometry(QtCore.QRect(30, 480, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.datenfusionbtn.setFont(font)
        self.datenfusionbtn.setObjectName("datenfusionbtn")
        self.ramanplot = QtWidgets.QGraphicsView(self.centralwidget)
        self.ramanplot.setGeometry(QtCore.QRect(170, 60, 391, 161))
        self.ramanplot.setObjectName("ramanplot")
        self.ramanbankplot = QtWidgets.QGraphicsView(self.centralwidget)
        self.ramanbankplot.setGeometry(QtCore.QRect(170, 250, 391, 161))
        self.ramanbankplot.setObjectName("ramanbankplot")
        self.brechzahlfenster = QtWidgets.QLCDNumber(self.centralwidget)
        self.brechzahlfenster.setGeometry(QtCore.QRect(600, 130, 161, 61))
        self.brechzahlfenster.setMouseTracking(False)
        self.brechzahlfenster.setObjectName("brechzahlfenster")
        self.brechzahlbankfenster = QtWidgets.QLCDNumber(self.centralwidget)
        self.brechzahlbankfenster.setGeometry(QtCore.QRect(600, 250, 161, 61))
        self.brechzahlbankfenster.setObjectName("brechzahlbankfenster")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(220, 420, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(400, 420, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(610, 420, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.ramanergebnis = QtWidgets.QLabel(self.centralwidget)
        self.ramanergebnis.setGeometry(QtCore.QRect(200, 480, 180, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ramanergebnis.setFont(font)
        self.ramanergebnis.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.ramanergebnis.setObjectName("ramanergebnis")
        self.brechergebnis = QtWidgets.QLabel(self.centralwidget)
        self.brechergebnis.setGeometry(QtCore.QRect(400, 480, 180, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.brechergebnis.setFont(font)
        self.brechergebnis.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.brechergebnis.setObjectName("brechergebnis")
        self.endergebnis = QtWidgets.QLabel(self.centralwidget)
        self.endergebnis.setGeometry(QtCore.QRect(600, 480, 180, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.endergebnis.setFont(font)
        self.endergebnis.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.endergebnis.setObjectName("endergebnis")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        #Btn function
        #self.

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.loadramanbtn.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.loadramanbtn.setText(_translate("MainWindow", "Load Raman"))
        self.loadbrechbtn.setText(_translate("MainWindow", "Load Brechzahl"))
        self.auswertungbtn.setText(_translate("MainWindow", "Auswertung"))
        self.detailbtn.setText(_translate("MainWindow", "Details"))
        self.datenfusionbtn.setText(_translate("MainWindow", "Daten Fusion"))
        self.label.setText(_translate("MainWindow", "Raman"))
        self.label_2.setText(_translate("MainWindow", "Brechungsindex"))
        self.label_3.setText(_translate("MainWindow", "Ergebnis"))
        self.ramanergebnis.setText(_translate("MainWindow", "Raman-Ergebnis"))
        self.brechergebnis.setText(_translate("MainWindow", "Bre-Ergebnis"))
        self.endergebnis.setText(_translate("MainWindow", "Endergebnis"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())


